config/routes.rb
Rails.application.routes.draw do
  root to: 'images#index'
  resources :images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :artist, presence: true
  validates :title, length: {minimum:3, maximum:20}
  validates :url, length: {minimum:1}
  validates :url, uniqueness: true
  validates_format_of :url, :with => URI::regexp(%w(http https))

  # private
  # def url_starts_http
  #   if Image.url
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :image_find, only: [:show, :destroy, :edit, :update]

  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to root_path
    else
      #redirect_to new_image_path
      render :new
    end
  end

  def edit
  end

  def update
    if @image.update_attributes(image_params)
      redirect_to image_path(@image)
    else
      render :edit
    end
  end

  def destroy
    @image.destroy
    redirect_to root_path
  end

  private

  def image_params
    params.require(:image).permit(:artist, :title, :url)
  end

  def image_find
    @image = Image.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image do |f| %>
  <p>
    <%= f.label "artist" %>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Shit" %>
  </p>
<%end%>

<% if @image.errors.any? %>
  <% @image.errors.full_messages.each do |msg| %>
    <p><%= "Yarrrrr walk the plank and try again! #{msg}!" %></p>
  <% end %>
<% end %>

app/views/images/_image.html.erb
<%= "Artist: #{image.artist}"  %><br>
<%= "Title: #{image.title}" %><br>
<%= link_to image_tag(image.url, height: 500, width: 500), image %><br>

app/views/images/edit.html.erb
<%= render 'form' %>

app/views/images/index.html.erb
<%= link_to "New Image", new_image_path %><br><br>

<% @images.each do |image| %>
  <%= render 'image', image: image %>
<%end%>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/images/show.html.erb
<%= render @image %>

<%= link_to "Home", root_path %> | <%= link_to "Edit", edit_image_path %> | <%= link_to "Delete", image_path, method: :delete, data: {confirm: "You sure, dog?"}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imageur</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>